
services:
  db: 
    image: postgres:17
    restart: always 
    environment:
      - POSTGRES_PASSWORD=passer
      - POSTGRES_USER=admin
      - POSTGRES_DB=zapp
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 10
    volumes:
      - pgdata:/var/lib/pgsql/data
    ports:
      - "5432:5432"

volumes:
  pgdata: